services:
  - type: web
    name: ub-jewellers-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false

